remote_theme:	Notepad
title:	Dallas Apple Admins
Description:	We are a group of Mac admins that gather regularly
logo:	site.png
default_bg:	920x920.jpg
timezone:	America/Chicago
readtime:         true
keywords:	apple, Mac, admin, Jamf, Munki, Casper, Management
