title: "Dallas Apple Admins"
email: steve@wood-family.net
description: >- # this means to ignore newlines until "baseurl:"
  Official blog for the Dallas Area Apple Admins group
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dallasappleadmins.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dallasmacadmns
github_username:  stevewood-tx

avatar: https://raw.githubusercontent.com/stevewood-tx/dallasappleadmins.github.io/master/assets/images/avatar.png

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

copyright:
  year:             2024
  name:             Dallas Apple Admins