remote_theme:	Notepad
title:	Dallas Apple Admins
logo:	site.png
default_bg:	920x920.jpg
timezone:	America/Chicago
description:	This is the home site for the Dallas Area Apple Admins. We meet regularly to further the skills of Mac management, and to provide our end users with the best experience possible.
readtime:         true
url:	http://www.dallasappleadmins.org
keywords:	apple, Mac, admin, Jamf, Munki, Casper, Management
